### PR TITLE
Sudo required - refinements

### PR DESCRIPTION
**Pull request by gilleyj**
Inclusion of sudo for completeness

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by till** [comment]
@gilleyj great! Can you update package.json with dependency and version bump?

**Comment by gilleyj** [comment]
I made min0rz change to addres issue https://github.com/till/nukify/issues/2

**Comment by gilleyj** [comment]
The sudo requirement should be replaced with a buff3r 0v3rrun **expl0itz**

**Comment by bluemaex** [comment]
:+1: :cupid:

**Comment by till** [comment]
Merged/rebase locally.

**Pull request closed without merging**
